---
floating_ip: "{{ hostvars[groups['fip'][0]]['ip_address'] }}"
primary_node: "{{ hostvars[groups['load_balancer'][0]] }}"
primary_name: "{{ primary_node.name }}"
primary_address: "{{ primary_node.ansible_default_ipv4.address }}"
secondary_node: "{{ hostvars[groups['load_balancer'][1]] }}"
secondary_name: "{{ secondary_node.name }}"
secondary_address: "{{ secondary_node.ansible_default_ipv4.address }}"
